### ISSUE TITLE
메인, 로그인, 회원가입 페이지 마크업 및 스타일 적용

### ISSUE THREAD

**Issue by who0803** [Company-People/Piece-Plan#1]
## Abstract
메인, 로그인, 회원가입 페이지 마크업 및 스타일 적용

## To Do
- [x] 메인 마크업
- [x] 로그인 마크업
- [x] 회원가입 마크업
- [x] 메인 스타일
- [x] 로그인 스타일
- [x] 회원가입 스타일

**Comment by eunoo1995** [comment]
굳잡 현진~
